<?php

declare(strict_types=1);

namespace App\Services;

use InvalidArgumentException;

/**
 * Turns a shop's extracted corporate identity into a Revoco brand theme overlay:
 * a `.wf-card[data-theme="<slug>"]` block overriding a subset of the `--wf-*`
 * token contract (see .claude/project/design/theming.md), plus a placement report.
 *
 * This is the deterministic, tested core of the design-adoption skill. The
 * (non-deterministic) scraping/extraction happens in the skill, which feeds
 * validated token values here. All output honours the token contract and never
 * overrides the accessibility-invariant tokens (the visible focus ring), so a
 * generated overlay can never regress a11y.
 */
final class ThemeOverlayGenerator
{
    /** Tokens carrying a font stack; every other token is validated as a colour. */
    private const FONT_TOKENS = ['--wf-font', '--wf-font-display'];

    /**
     * Accessibility-invariant tokens the generator refuses to override, so an
     * overlay can never remove the visible focus ring (theming.md a11y invariants).
     *
     * @var list<string>
     */
    private const A11Y_LOCKED_TOKENS = ['--wf-focus-ring'];

    private string $contractCssPath;

    public function __construct(string $contractCssPath = '')
    {
        $this->contractCssPath = $contractCssPath !== ''
            ? $contractCssPath
            : resource_path('css/withdrawal.css');
    }

    /**
     * @param  array<string, string>  $tokens  --wf-* token name => value.
     *
     * @throws InvalidArgumentException on an invalid slug, token, value or logo URL.
     */
    public function generate(
        string $slug,
        array $tokens,
        ?string $logoUrl = null,
        ?string $brandName = null,
    ): ThemeOverlay {
        $this->assertValidSlug($slug);
        $this->assertValidLogoUrl($logoUrl);

        $contract = $this->loadContract();

        /** @var array<string, string> $emitted */
        $emitted = [];
        foreach ($tokens as $token => $value) {
            if (! in_array($token, $contract, true)) {
                throw new InvalidArgumentException(
                    "Unknown --wf-* token: {$token} (not in the withdrawal.css contract).",
                );
            }
            if (in_array($token, self::A11Y_LOCKED_TOKENS, true)) {
                throw new InvalidArgumentException(
                    "Refusing to override accessibility-locked token {$token}.",
                );
            }
            $this->assertValidValue($token, $value);
            $emitted[$token] = $value;
        }

        return new ThemeOverlay(
            css: $this->renderCss($slug, $emitted),
            report: $this->buildReport($slug, $logoUrl, $brandName),
            emittedTokens: array_keys($emitted),
            warnings: $emitted === []
                ? ['No brand tokens were provided — the overlay is empty and every token falls through to the neutral default.']
                : [],
        );
    }

    /**
     * @param  array<string, string>  $tokens
     */
    private function renderCss(string $slug, array $tokens): string
    {
        $lines = [
            '/* Revoco brand theme overlay — generated by `php artisan revoco:make-theme`.',
            "   Place it per .claude/project/design/theming.md and select it with APP_THEME={$slug}.",
            '   Do NOT commit this file to the public Revoco repo (brand assets stay private). */',
            ".wf-card[data-theme=\"{$slug}\"] {",
        ];
        foreach ($tokens as $token => $value) {
            $lines[] = "    {$token}: {$value};";
        }
        $lines[] = '}';

        return implode("\n", $lines)."\n";
    }

    /**
     * @return list<string>
     */
    private function buildReport(string $slug, ?string $logoUrl, ?string $brandName): array
    {
        $report = [
            'Placement: put this overlay in your private infra repo / deployment mount (see theming.md — the public/private split). Never commit it to the public Revoco repo.',
            "Selection: set APP_THEME={$slug} in your deployment .env.",
        ];
        $report[] = $logoUrl !== null
            ? "Logo: set REVOCO_LOGO_URL={$logoUrl} in .env — rendered as an <img> in the reserved .wf-logo slot."
            : 'Logo: no --logo-url given. Set REVOCO_LOGO_URL in .env, or add --wf-logo-img/-w/-h to the overlay.';
        if ($brandName !== null) {
            $report[] = "Brand name: set REVOCO_BRAND_NAME={$brandName} in .env.";
        }
        $report[] = 'Accessibility: the neutral focus ring and reduced-motion handling are preserved (not overridden). Verify your accent contrasts sufficiently with text and the focus ring.';
        $report[] = 'Review the rendered form before going live — you own the final appearance.';

        return $report;
    }

    /**
     * The token contract is the set of `--wf-*` custom properties defined in the
     * neutral stylesheet — the single source of truth an overlay may override.
     *
     * @return list<string>
     */
    private function loadContract(): array
    {
        if (! is_file($this->contractCssPath)) {
            throw new InvalidArgumentException(
                "Token contract CSS not found at {$this->contractCssPath}.",
            );
        }

        $css = (string) file_get_contents($this->contractCssPath);
        if (preg_match_all('/--wf-[a-z0-9-]+/', $css, $matches) === false) {
            return [];
        }

        return array_values(array_unique($matches[0]));
    }

    private function assertValidSlug(string $slug): void
    {
        if (preg_match('/^[a-z][a-z0-9-]{0,40}$/', $slug) !== 1) {
            throw new InvalidArgumentException(
                'Invalid --slug: use lowercase letters, digits and hyphens, starting with a letter (max 41 chars).',
            );
        }
    }

    private function assertValidValue(string $token, string $value): void
    {
        $isFont = in_array($token, self::FONT_TOKENS, true);
        $ok = $isFont ? $this->isValidFont($value) : $this->isValidColour($value);
        if (! $ok) {
            $kind = $isFont ? 'font value' : 'colour';
            throw new InvalidArgumentException("Invalid {$kind} for {$token}: '{$value}'.");
        }
    }

    /**
     * Accept hex, rgb()/rgba()/hsl()/hsla() and named colours, and reject anything
     * that could break out of the CSS declaration (a scraped value is untrusted).
     */
    private function isValidColour(string $value): bool
    {
        $value = trim($value);
        if ($value === '' || strlen($value) > 64) {
            return false;
        }
        if (preg_match('/[;{}<>\\\\]|\/\*|\*\//', $value) === 1) {
            return false;
        }
        if (preg_match('/^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/', $value) === 1) {
            return true;
        }
        if (preg_match('/^(?:rgb|rgba|hsl|hsla)\([0-9.,%\s\/]+\)$/i', $value) === 1) {
            return true;
        }

        return preg_match('/^[a-zA-Z]+$/', $value) === 1;
    }

    /**
     * Accept a font-family stack (names, quotes, commas) and reject CSS-breaking
     * characters — same injection guard as colours.
     */
    private function isValidFont(string $value): bool
    {
        $value = trim($value);
        if ($value === '' || strlen($value) > 200) {
            return false;
        }
        if (preg_match('/[;{}<>\\\\]|\/\*|\*\//', $value) === 1) {
            return false;
        }

        return preg_match('/^[a-zA-Z0-9 ,\'"\-.]+$/', $value) === 1;
    }

    private function assertValidLogoUrl(?string $logoUrl): void
    {
        if ($logoUrl === null) {
            return;
        }
        $scheme = parse_url($logoUrl, PHP_URL_SCHEME);
        if (filter_var($logoUrl, FILTER_VALIDATE_URL) === false || ! in_array($scheme, ['http', 'https'], true)) {
            throw new InvalidArgumentException(
                "Invalid --logo-url: '{$logoUrl}' is not a valid http(s) URL.",
            );
        }
    }
}
